package rates;
// Generated Dec 7, 2010 4:45:17 PM by Hibernate Tools 3.2.1.GA



/**
 * Rates generated by hbm2java
 */
public class Rates  implements java.io.Serializable {


     private long id;
     private String date;
     private String bank;
     private String currency;
     private Float rate;

    public Rates() {
    }

	
    public Rates(long id) {
        this.id = id;
    }
    public Rates(long id, String date, String bank, String currency, Float rate) {
       this.id = id;
       this.date = date;
       this.bank = bank;
       this.currency = currency;
       this.rate = rate;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public Float getRate() {
        return this.rate;
    }
    
    public void setRate(Float rate) {
        this.rate = rate;
    }




}


